### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by mweinelt** [Mitame/nixos-ipu6#1]
Hi, I just found your repository after packaging things up for nixpkgs at https://github.com/NixOS/nixpkgs/pull/212799.

Do you have some instructions on how to set up the system to make use of all these packages? Did you succeed in getting the camera running? Did you succeed in getting motion sensing working?

**Comment by mindtheegab** [comment]
m,ight be late but this is a flake repo so you install it using

nix profile install /path/to/flake

but yopu have to enable flakes first 

```Temporary
Add --experimental-features 'nix-command flakes' when calling the nix command.

Permanent
Edit either ~/.config/nix/nix.conf or /etc/nix/nix.conf and add:

experimental-features = nix-command flakes
Here's a handy copy-paste:

mkdir -p ~/.config/nix
echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
If the Nix installation is in multi-user mode, don’t forget to restart the nix-daemon.

NixOS
On NixOS set the following options in configuration.nix and run nixos-rebuild.

{ pkgs, ... }: {
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
}
```

**Comment by mweinelt** [comment]
Yep, very late. With NixOS 23.05 we have `hardware.ipu6.enable` to toggle support.

**Comment by mindtheegab** [comment]
that doesnt work for me

**Comment by mweinelt** [comment]
See https://github.com/NixOS/nixpkgs/issues/225743.
